method: random
metric:
  name: loss
  goal: minimize
parameters:
  target_path:
    value: data/blood/blood-28.png
  img_size:
    value: 28
  padding:
    value: 0
  min_steps:
    #distribution: int_uniform
    #min: 30
    #max: 75
    values: [30, 40, 50, 60, 70]
  max_steps:
    #distribution: int_uniform
    #min: 80
    #max: 120
    values: [80, 90, 100, 110]
  n_channels:
    #distribution: int_uniform
    #min: 8
    #max: 32
    values: [8, 12, 16, 20, 24]
  num_h_channels:
    #distribution: int_uniform
    #min: 64
    #max: 256
    values: [32, 64, 128, 256, 512]
  fire_rate:
    #distribution: uniform
    #min: 0.1
    #max: 1.0
    values: [0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]
  batch_size:
    value: 8
  pool_size:
    value: 1024
  learning_rate:
    value: 0.001
  iterations:
    value: 1000
  damage:
    value: True
  damage_start:
    values: [100, 300, 500, 700]
  clip_value:
    value: 1.0
  model_path:
    value: models/nca_model.pth
  loss_function:
    value: hinge # Options: "mse", "manhattan", "hinge", "ssim", "combined_ssim_l1"
  filter_name:
    value: gaussian  # Options: "identity", "sobel", "laplacian", "gaussian"

