batch_size: 8
clip_value: 1
damage: true
damage_start: 700
filter_name: sobel_identity
fire_rate: 0.2
img_size: 28
iterations: 1000
learning_rate: 0.001
loss_function: mse
max_steps: 90
min_steps: 50
model_path: models/best_configs/ra73fs60_best_nca_model.pth
n_channels: 16
num_h_channels: 64
padding: 0
pool_size: 1024
target_path: data/blood/blood-28.png
